name: aplikasi_manajemen_keuangan
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  firebase_auth: ^5.1.1
  firebase_core: ^3.1.1
  cloud_firestore: ^5.0.2
  provider: ^6.1.2
  image_picker: ^1.1.1
  date_picker_timeline: ^1.2.5
  firebase_storage: ^12.1.0
  uuid: ^3.0.6
  intl: ^0.18.1
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
